language: python
python:
  - "3.9"


addons:
  sonarcloud: true


script:
  - pytest
  - pip verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ericaudizzio -Dsonar.login=$SONAR

notifications:
  email:
    recipients:
      - erixaudixio@gmail.com