language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
    organization: "ericaudizzio"
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  - sonar-scanner
  - pytest

