language: python
python:
  - "3.9"


addons:
  sonarcloud: true


script:
  - pytest
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=ericaudizzio -Dsonar.projectKey=Entorno_1 -Dsonar.sources='./' -X

notifications:
  email:
    recipients:
      - erixaudixio@gmail.com