language: python
python:
  - "3.9"


addons:
  sonarcloud: true


script:
  - pytest
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=EricAudizzio -Dsonar.projectKey= Entorno_1 -Dsonar.sources='C:\Users\user\Desktop\proyecto_is'  -X

notifications:
  email:
    recipients:
      - erixaudixio@gmail.com