language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud: true

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ericaudizzio -Dsonar.login=$SONAR_TOKEN -X
  - pytest

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: main

notifications:
  slack: miprimerentono:$slack_token