language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
addons:
  sonarcloud:
      organization: ericaudizzio

script:
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=ericaudizzio -Dsonar.login=$SONAR_TOKEN -X
  - pytest

